name: Apply Copyright

on:
  pull_request:
    branches: [ main ]

jobs:

  apply-copyright:
    name: ©️ Apply Copyright
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Apply Copyright
        run: ./gradlew spotlessApply --stacktrace