name: Build Main Branch

on:
  pull_request:
    branches: [ main ]

jobs:

  apply-copyright:
    name: ©️ Apply Copyright
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Apply Copyright
        run: ./gradlew :daraja:spotlessApply --stacktrace

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    needs: [apply-copyright]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew :daraja:build --stacktrace

  lint-check:
    name: 🔍 Lint Check
    runs-on: ubuntu-latest
    needs: [apply-copyright]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Lint check
        run: ./gradlew :daraja:ktlintCheck --stacktrace

  unit-tests:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    needs: [apply-copyright]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Execute unit tests
        run: ./gradlew :daraja:allTests --stacktrace

#      - name: Generate test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: unit_tests_report.html
#          path: androidApp/build/reports/tests/testDebugUnitTest/