name: Publish iOS Library

on:
  workflow_dispatch:
  push:
    branches: [clean-up]

jobs:
  call-kmmbridge-publish:
    name: 🚀 Publish iOS Library
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6