name: Publish Multiplatform Libraries

on:
  push:
    branches: [ publish-lib ]

jobs:

  deploy-android:
    name: 🚀 Sign and Publish Android Library
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Sign and Publish Android Library
        run: ./gradlew :daraja:publishAndroidReleasePublicationToSonatypeRepository --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          POM_NAME: ${{ secrets.POM_NAME }}
          POM_DESCRIPTION: ${{ secrets.POM_DESCRIPTION }}
          POM_URL: ${{ secrets.POM_URL }}
          POM_DEVELOPER_ID: ${{ secrets.POM_DEVELOPER_ID }}
          POM_DEVELOPER_NAME: ${{ secrets.POM_DEVELOPER_NAME }}
          POM_DEVELOPER_EMAIL: ${{ secrets.POM_DEVELOPER_EMAIL }}
          POM_LICENSE_NAME: ${{ secrets.POM_LICENSE_NAME }}
          POM_LICENSE_URL: ${{ secrets.POM_LICENSE_URL }}
          POM_ISSUE_URL: ${{ secrets.POM_ISSUE_SYSTEM }}
          POM_SCM_CONNECTION: ${{ secrets.POM_SCM_CONNECTION }}
          POM_SCM_DEVELOPER_CONNECTION: ${{ secrets.POM_SCM_DEVELOPER_CONNECTION }}
          POM_SCM_URL: ${{ secrets.POM_SCM_URL }}
          SIGNING_ID: ${{ secrets.SIGNING_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}