name: Publish iOS Library

on:
  workflow_dispatch:

  push:
    branches: [iOS-support]

jobs:

  build:
    name: 🚀 Create Swift Package
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Create Swift Package
        run: ./gradlew :daraja:createSwiftPackage --stacktrace

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: daraja-multiplatform-spm
          path: swiftpackage/