name: Publish iOS Library

on:
  workflow_dispatch:
  push:
    branches: [ci-cd]

jobs:
  publish-iOS:
    name: 🚀 Publish iOS Library
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6