name: Publish iOS Library

on:
  workflow_dispatch:
    inputs:
      iOSVersionName:
        description: 'iOS Version prefix (eg. _.9.0)'
        required: true

env:
  IOS_PREFIX: ${{ github.event.inputs.iOSVersionName }}


jobs:
  publish-iOS:
    name: 🚀 Publish iOS Library
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6