name: Sign and Publish iOS Library

on:
  push:
    branches: [ iOS-support ]

jobs:
  call-kmmbridge-publish:
    name: 🚀 Publish iOS Library
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6